/*
 * Copyright 2026 bidet-ai contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.ai.edge.gallery.bidet.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One persisted brain-dump session. Phase 4A unit of restore + export.
 *
 *  - [sessionId] is the UUID generated by [com.google.ai.edge.gallery.bidet.service.RecordingService]
 *    when the recording starts. It is also the directory name under
 *    `${getExternalFilesDir(null)}/sessions/<sessionId>/` for chunks + the WAV.
 *  - [rawText] is the merged transcript snapshot at recording stop (from
 *    [com.google.ai.edge.gallery.bidet.transcript.TranscriptAggregator.currentText]). The live
 *    screen also writes intermediate snapshots so a crash mid-recording leaves a partial row
 *    rather than nothing.
 *  - [cleanCached] / [analysisCached] / [foraiCached] are tab outputs. Null until the user
 *    opens the corresponding tab; non-null afterwards so re-opening the session doesn't
 *    require regeneration.
 *  - [audioWavPath] is filled in once
 *    [com.google.ai.edge.gallery.bidet.audio.WavConcatenator.concatenateChunksToWav] has
 *    fused the per-chunk PCM files into one playable WAV. Null while still recording or if
 *    concat hasn't run.
 *
 * The DAO is exposed via [BidetSessionDao]; the database via [BidetDatabase].
 */
@Entity(tableName = "bidet_sessions")
data class BidetSession(
    @PrimaryKey val sessionId: String,
    val startedAtMs: Long,
    val endedAtMs: Long? = null,
    val durationSeconds: Int = 0,
    val rawText: String = "",
    val cleanCached: String? = null,
    val analysisCached: String? = null,
    val foraiCached: String? = null,
    /**
     * v20 (2026-05-11): cached Clean-for-judges output. Persists across re-opens so an
     * 800-1200 word contest writeup that took 6-10 minutes to decode on Tensor G3 CPU
     * doesn't have to regenerate. Schema v3 (Migration 2→3 in
     * [BidetDatabase.MIGRATION_2_3]). Null until the user taps Generate on the Judges tab.
     */
    val judgesCached: String? = null,
    val audioWavPath: String? = null,
    val chunkCount: Int = 0,
    val notes: String? = null,
    /**
     * Bug-3 fix (2026-05-10): per-merge counter so the History UI can render
     * "Transcribing N of M chunks…" while the worker is still draining after the user
     * tapped Stop. Updated every time [com.google.ai.edge.gallery.bidet.transcript.TranscriptAggregator]
     * commits a merge to the DB. At finalize time it equals [chunkCount] (the queue is
     * drained); during the transcribing-after-stop window it lags behind by however many
     * chunks remain in the queue.
     *
     * Schema v2 (Migration 1→2 in [BidetDatabase.MIGRATION_1_2]). Pre-v2 rows backfill to 0;
     * since they were finalized under v1 (which set endedAtMs), the History progress
     * indicator's `endedAtMs IS NULL` condition is false and `mergedChunkCount` is never
     * read for those rows.
     */
    val mergedChunkCount: Int = 0,
)
